movie/urls.py
from django.urls import path
from . import views
# 지금 내가 있는 폴더에서 views라는 파이썬 파일을 가져올거야!


# urlpatterns = [
#      path('home/', views.home, name='home'), #메인페이지
#      path('<int:pk>', views.recommend_movies, name='recommend_movies'),
#      path('movie/comment/create/<int:id>',
#          views.comment_create, name='comment-create'),
#      path('<int:pk>/comment/delete/<int:id>',
#          views.comment_delete, name='comment-delete'),
#      path('<int:movie_pk>/likes', views.likes, name='likes'),
# ]

app_name = "movie"

urlpatterns = [ 
    path('', views.main, name='main'), 
    path('home/', views.home, name='home'), 
    path('<int:pk>', views.recommend_movies, name='recommend_movies'), 
    path('movie/comment/create/<int:id>', views.comment_create, name='comment-create'), 
    path('<int:pk>/comment/delete/<int:id>', views.comment_delete, name='comment-delete'), 
    path('<int:pk>/likes', views.likes, name="likes"), 
    path('search/', views.search, name="search"), ]

team_django_netflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('', include("movie.urls")),
]


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
# user/urls.py
from django.urls import path  # sns/urls.py 연동
from . import views  # 같은 폴더내 views.py 연동

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-in/', views.sign_in, name='sign-in'),
    path('logout/', views.logout, name='logout'),
]

movie/models.py
from turtle import ondrag
from django.db import models
from user.models import UserModel
from django.conf import settings


COMMENT_POINT_CHOICES = (
    ('1', 1),
    ('2', 2),
    ('3', 3),
    ('4', 4),
    ('5', 5),
    ('6', 6),
    ('7', 7),
    ('8', 8),
    ('9', 9),
    ('10', 10),
)


# 장르 모델
class GenreModel(models.Model):
    class Meta:
        db_table = 'genre'

    def __str__(self):
        return self.genre_name

    genre_name = models.CharField(max_length=50, null=True)


# 영화 정보 DB
class MovieModel(models.Model):
    class Meta:
        db_table = "movie"

    title = models.CharField(max_length=256, blank=True, null=True)
    url = models.CharField(max_length=256, blank=True, null=True)
    imgurl = models.CharField(max_length=256, blank=True, null=True)
    genre = models.ManyToManyField(GenreModel, related_name='genre')
    age = models.CharField(max_length=256, blank=True, null=True)
    runningtime = models.CharField(max_length=256, blank=True, null=True)
    opendate = models.CharField(max_length=256, blank=True, null=True)
    actors = models.CharField(max_length=256, blank=True, null=True)
    rate = models.FloatField(blank=True, null=True)
    story = models.TextField(blank=True, null=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)


# 영화 댓글 모델
class MovieComment(models.Model):
    class Meta:
        db_table = 'comment'

    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    movie = models.ForeignKey(MovieModel, on_delete=models.CASCADE)
    comment = models.CharField(max_length=256)
    user_rate = models.CharField(max_length=5, choices=COMMENT_POINT_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

movie/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import *
from . import recommender_ml
from . import collab_recommender
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

# Create your views here.

def main(request):
    user = request.user.is_authenticated
    if user:
        return redirect('/home')
    else:
        return redirect('/sign-in')





# 메인페이지
@login_required
def home(request):
    if request.method == 'GET':
        print("user id =", end=""), print(request.user.id)
        user_based = collab_recommender.collab
        movies = user_based.collab_recommend(request.user.id)
        # print(request.user)
        # print(request.user.id)
        
        rec ={}
        for movie in movies:
            genres = movie.genre.all()
            rec[movie] = genres

        # 전체 다불러옴
        # movies = MovieModel.objects.all().order_by('-pk')
        # infos = {}
        # genre_list = []
        # for movie in movies:
        #     genres = movie.genre.all()
        #     infos[movie] = genres
        # print(infos)
        
        # 찜한 컨텐츠
        user = request.user
        user_like = list(user.like_articles.all())
        likes = {}
        
        
        
        for like in user_like:
            genre = like.genre.all()
            likes[like] = genre

        # 평점 별 줄세우기
        rate_ranking = MovieModel.objects.all().order_by('-rate')[:31]
        ranking = {}
        rate_genres = []
        for rank in rate_ranking:
            genre = rank.genre.all()
            ranking[rank] = genre

        return render(request, 'movie/home.html', {'rec':rec, 'likes':likes, 'ranking':ranking})


# 상세페이지 상, 중, 하
@login_required
def recommend_movies(request, pk):
    if request.method == "GET":
        # 상
        movie_detail = MovieModel.objects.get(pk=pk)
        # print("movie_detail: ", movie_detail)
        
        # 중 - 댓글
        page = request.GET.get('page', 1)
        comment_list = MovieComment.objects.filter(
            movie=pk).order_by('-created_at')
        paginator = Paginator(comment_list, 3)
        comments = paginator.get_page(page)

        # 하 - 추천
        recommend = recommender_ml.similarmovies
        movies = recommend.content_based(pk-1)
        infos ={}
        for movie in movies:
            genres = movie.genre.all()
            infos[movie] = genres
    
        return render(request, 'movie/detail.html', {'movie':movie_detail, 'comment_list': comments, 'infos': infos})


# 댓글 작성
@login_required
def comment_create(request, id):
    if request.method == 'POST':
        comment = request.POST.get("comment", "")
        rate = request.POST.get("user_rate", "")

        # user = TestUser.objects.get(id=id)
        movie = MovieModel.objects.get(pk=id)

        comment_db = MovieComment()
        comment_db.user = request.user
        comment_db.movie = movie
        comment_db.comment = comment
        comment_db.user_rate = rate
        comment_db.save()

        return redirect("/"+str(id))


# 댓글 삭제
@login_required
def comment_delete(request,pk, id):
    comment = MovieComment.objects.get(id=id)
    #comment_id = comment.movie_id.id
    comment.delete()
    return redirect('/' + str(pk))


# 좋아요
@login_required
def likes(request, pk):
    movie = get_object_or_404(MovieModel, pk=pk)

    if movie.like_users.filter(pk=request.user.pk).exists():
        movie.like_users.remove(request.user)
    else:
        movie.like_users.add(request.user)
    return redirect('movie:recommend_movies', pk)



# 검색
def search(request):
    if 'kw' in request.GET:
        query = request.GET.get('kw', '')
        movies = MovieModel.objects.all().filter(
            Q(title__icontains=query) |
            Q(actors__icontains=query)
        )
        infos = {}
        genre_list = []
        for movie in movies:
            genres = movie.genre.all()
            infos[movie] = genres
            
    
        
    return render(request, 'movie/search.html', {'query':query, 'movies':movies, 'genres':genres, 'infos': infos})

templates/movie/detail.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>

    <script src="https://kit.fontawesome.com/b57dd44d80.js" crossorigin="anonymous"></script>
    {# 상세페이지 상단 #}
    <link rel="stylesheet" href="{% static 'css/movie_info.css' %}" />
    {# 상세페이지 중단 #}
    <link rel="stylesheet" href="{% static 'css/comment.css' %}" />
    {# 상세페이지 하단 #}
    <link rel="stylesheet" href="{% static 'css/movie_list.css' %}" />

</head>

<body>
    <div class="overlay">
        <div class="header">
            <a class="logo" href="/">NETFLIX</a>
            <div class="nav">
                <a class="nav-item" href="/">홈</a>
            </div>
            <div class="menu">
                <div id="search">
                    <form method="get" action="{% url 'movie:search' %}" >
                        <input type="search" name="kw" placeholder="검색">
                    </form>
                </div>
                <div class="menu-item"> {{user.username}} </div>
                <a class="menu-item" href={% url 'logout' %} style="color:white; text-decoration-line: none;">
                    Logout
                </a>
            </div>
        </div>
    </div>

    {# 상세페이지 상단 #}
    <div class="img-box">
        <a href="{{movie.url}}"> <img src="{{movie.imgurl}}"> </a>
    </div>
    <main>
        <div class="description">
            <h1>{{movie.title}}</h1>
            <h3> {{movie.age}} / {{movie.actors}}/ {{movie.rate}}</h3>
            <p>{{movie.story}}</p>
            <div class="age-info">
                <i class="fa-solid fa-rotate-right"></i>
                <div class="age">
                    {{movie.age}}
                </div>
            </div>
            <div class="buttons">
                <div>
                    <form action="{% url 'movie:likes' movie.pk %}" method='POST'>
                        {% csrf_token %}
                        {% if user in movie.like_users.all %}
                        <button class="play" value="좋아요 취소"><span>취소</span></button>
                        {% else %}
                        <button class="play" value="좋아요"><span>좋아요</span></button>
                        {% endif %}
                    </form>
                </div>
                <button class="detail"><i class="fa-solid fa-circle-info"></i>{{movie.like_users.count}}명이
                    좋아합니다.</button>
            </div>
        </div>
    </main>

    {# 상세페이지 중단 #}
    <div class="comment">
        <div class="review_text_box">REVIEW</div>
        {# 댓글 작성하는 곳 #}
        <form class="comment_box" action="/movie/comment/create/{{ movie.id }}" method="post">
            {% csrf_token %}
            <div class="email_and_rate">
                <h4 class="email_box">{{ user.user_id }}</h4>
                <div>
                    <label class="rate_box_name" for="user_rate">평점 :</label>
                    <select class="rate_option" id="user_rate" name="user_rate">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5" selected>5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>
            </div>
            <div class="comment_text_box">
                <input type="text" class="comment_text" id='comment' name='comment' placeholder="댓글을 작성 해 주세요." />
            </div>
            <div class="button_box">
                <button type="submit" class="submit_button">등록</button>
            </div>
        </form>

        {# 작성된 댓글 불러오기 #}
        {% for comment in comment_list %}
        <div class="comment_list">
            <div class="name_and_delete">
                <h4> {{ comment.user }} </h4>
                {% if comment.user == user %}
                <a href="/{{movie.pk}}/comment/delete/{{ comment.id }}">
                    <span>삭제</span>
                </a>
                {% endif %}
            </div>
            <div class="comment_and_rate">
                <p> {{ comment.comment }} </p>
                <p> {{ comment.user_rate }} 점 <span> - {{ comment.created_at | timesince }} 전</span></p>
            </div>
        </div>
        {% endfor %}

        <ul class="comment_list_ul">
            <!-- 이전 페이지 -->
            {% if comment_list.has_previous %}
            <li>
                <a href="?page={{ comment_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li>
                <a tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}

            <!-- 페이지 리스트 -->
            {% for page_number in comment_list.paginator.page_range %}
            {% if page_number == comment_list.number %}
            <li>
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li>
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if comment_list.has_next %}
            <li>
                <a href="?page={{ comment_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li>
                <a tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>

    {# 상세페이지 하단 #}
    <div class="recommend_movies">
        <div class="wrapper">
            <div class="list-title">관련 영화 추천</div>
            <div class="carousel">
                <div class="carouselbox relation">
                    {% for movie, genres in infos.items %}
                    <div class="content">
                        <a href="{% url 'movie:recommend_movies' movie.pk %}">
                            <img class="img-0 slider-img" src="{{movie.imgurl}}">
                            <!--Hover Content-->
                            <div class="video_content">
                                <div class="play_btn">
                                    <div class="vid_name">{{movie.title}}</div>
                                    <div class="vid_detail">
                                        <ul class="vid_list">
                                            <li class="c_green">{{movie.rate}}</li>
                                            <li class="br_round">{{movie.age}}</li>
                                            <li>{{movie.runningtime}}</li>
                                        </ul>
                                    </div>
                                    <div class="vid_category">
                                        <ul class="vid_list">
                                            {% for genre in genres%}
                                            <li>{{genre.genre_name}}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <button class="switchLeft sliderButton" onclick="movie_related.sliderScrollLeft()"><</button>
                <button class="switchRight sliderButton" onclick="movie_related.sliderScrollRight()">></button>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.0.0-alpha.1/axios.js"></script>
        <script src="../../static/js/index.js"></script>
    </div>

    {# footer #}
    <footer>
        <div class="wrap">
            <div class="social-icons">
                <i class="fa-brands fa-facebook-square"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-youtube"></i>
            </div>
            <div class="options">
                <div class="option">자막 및 음성</div>
                <div class="option">음성 지원</div>
                <div class="option">고객 센터</div>
                <div class="option">기프트카드</div>
                <div class="option">미디어 센터</div>
                <div class="option">투자 정보(IR)</div>
                <div class="option">입사 정보</div>
                <div class="option">이용 약관</div>
                <div class="option">개인 정보</div>
                <div class="option">법적 고지</div>
                <div class="option">쿠키 설정</div>
                <div class="option">회사 정보</div>
                <div class="option">문의하기</div>
            </div>
        </div>
    </footer>
</body>

</html>
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete

templates/movie/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAIN</title>
    <script src="https://kit.fontawesome.com/b57dd44d80.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../static/css/movie_list.css"/>
    <script src="../../static/js/play.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <!-- 비디오와 상단바 -->
    <div class="home">
        <!-- 비디오 -->
        <video
        src="../../static/video/범죄도시2.mp4"
        autoplay
        width: 80%
        height: 80%
        controls
        ></video>
        <!-- overlay -->
        <div class="overlay">
            <!-- 상단바 -->
            <div class="header">
                <a class="logo" href="/" style="text-decoration-line: none;">NETFLIX</a>
                <div class="nav">
                    <a class="nav-item" href="/">홈</a>
                    <a class="nav-item" href="#rate-ranking">상위 평점 영화</a>
                    <a class="nav-item" href="#now_hottest">New! 요즘 대세영화</a>
                    <a class="nav-item" href="#like-contents">내가 찜한 콘텐츠</a>
                </div>
                <div class="menu">
                    <div id="search">
                    <form method="get" action="{% url 'movie:search' %}" >
                        <input type="search" name="kw" placeholder="검색">
                    </form>
                    </div>
                    <div class="menu-item"> {{user.username}} </div>
                    <a class="menu-item" href={% url 'logout' %} style="color:white; text-decoration-line: none;">
                        Logout
                    </a>
                </div>
            </div>
            <!-- 인기 영화 띄우기 -->
            <div class="banner">
                <div class="series">  </div>
                <div class="title" style="margin-top:40px">범죄도시 2</div>
                <div class="badge"><b>한국에서 콘텐츠 순위 1위</b></div>
                <div class="description">
                    “느낌 오지? 이 놈 잡아야 하는 거”
                    가리봉동 소탕작전 후 4년 뒤,
                    금천서 강력반은 베트남으로 도주한 용의자를 인도받아 오라는 미션을 받는다.
                    괴물형사 ‘마석도’(마동석)와 ‘전일만’(최귀화) 반장은 현지 용의자에게서 수상함을 느끼고,
                    그의 뒤에 무자비한 악행을 벌이는 ‘강해상’(손석구)이 있음을 알게 된다.
                    ‘마석도’와 금천서 강력반은 한국과 베트남을 오가며
                    역대급 범죄를 저지르는 ‘강해상’을 본격적으로 쫓기 시작하는데...
                    나쁜 놈들 잡는 데 국경 없다!
                    통쾌하고 화끈한 범죄 소탕 작전이 다시 펼쳐진다!
                </div>
                <div class="buttons">
                    <div class="white-button" onclick="play()">
                        <i class="fa-solid fa-play"></i>
                        재생
                    </div>
                    <div class="gray-button">
                        <i class="fa-solid fa-circle-info"></i>
                        상세정보
                    </div>
                </div>
                <div class="extra">
                    <div class="replay-button" onclick="play()">
                        <i class="fa-solid fa-arrow-rotate-left"></i>
                    </div>
                    <div class="rating"></div>
                </div>
                </div>
        </div>
    </div>
    <!-- 카테고리 -->
    <div class="category-list" style='margin-top:500px'>
        <div clas="wrapper">
            <div class="list-title" id="now_hottest">지금 뜨는 컨텐츠</div>
            <div class="carousel">s
                <div class="carouselbox first">
                    {% for movie, genres in rec.items %}
                        <div class="content">
                            <a href="{% url 'movie:recommend_movies' movie.pk %}">
                                <img class="img-0 slider-img" src="{{movie.imgurl}}">
                                <!--Hover Content-->
                                <div class="video_content">
                                    <div class="play_btn">
                                        <div class="vid_name">{{movie.title}}</div>
                                        <div class="vid_detail">
                                            <ul class="vid_list">
                                                <li class="c_green">{{movie.rate}}</li>
                                                <li class="br_round">{{movie.age}}</li>
                                                <li>{{movie.runningtime}}</li>
                                            </ul>
                                        </div>
                                        <div class="vid_category">
                                            <ul class="vid_list">
                                                {% for genre in genres%}
                                                <li>{{genre.genre_name}}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <button class="switchLeft sliderButton" onclick="recommend.sliderScrollLeft()"><</button>
                <button class="switchRight sliderButton" onclick="recommend.sliderScrollRight()">></button>
            </div>
        </div>
        <div class="wrapper">
            <div class="list-title" id="like-contents">{{user}}님이 찜한 컨텐츠</div>
            <div class="carousel">
                <div class="carouselbox second">
                    {% for movie, genres in likes.items %}
                        <div class="content">
                            <a href="{% url 'movie:recommend_movies' movie.pk %}">
                                <img class="img-0 slider-img" src="{{movie.imgurl}}">
                                <!--Hover Content-->
                                <div class="video_content">
                                    <div class="play_btn">
                                        <div class="vid_name">{{movie.title}}</div>
                                        <div class="vid_detail">
                                            <ul class="vid_list">
                                                <li class="c_green">{{movie.rate}}</li>
                                                <li class="br_round">{{movie.age}}</li>
                                                <li>{{movie.runningtime}}</li>
                                            </ul>
                                        </div>
                                        <div class="vid_category">
                                            <ul class="vid_list">
                                                {% for genre in genres%}
                                                <li>{{genre.genre_name}}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <button class="switchLeft sliderButton" onclick="userlike.sliderScrollLeft()"><</button>
                <button class="switchRight sliderButton" onclick="userlike.sliderScrollRight()">></button>
            </div>
        </div>
        <div class="wrapper">
            <div class="list-title" id="rate-ranking">평점 높은 영화</div>
            <div class="carousel">
                <div class="carouselbox third">
                    {% for movie, genres in ranking.items %}
                        <div class="content">
                            <a href="{% url 'movie:recommend_movies' movie.pk %}">
                                <img class="img-0 slider-img" src="{{movie.imgurl}}">
                                <!--Hover Content-->
                                <div class="video_content">
                                    <div class="play_btn">
                                        <div class="vid_name">{{movie.title}}</div>
                                        <div class="vid_detail">
                                            <ul class="vid_list">
                                                <li class="c_green">{{movie.rate}}</li>
                                                <li class="br_round">{{movie.age}}</li>
                                                <li>{{movie.runningtime}}</li>
                                            </ul>
                                        </div>
                                        <div class="vid_category">
                                            <ul class="vid_list">
                                                {% for genre in genres%}
                                                <li>{{genre.genre_name}}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <button class="switchLeft sliderButton" onclick="ranking.sliderScrollLeft()"><</button>
                <button class="switchRight sliderButton" onclick="ranking.sliderScrollRight()">></button>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.0.0-alpha.1/axios.js"></script>
        <script src="../../static/js/index.js"></script>
    </div>
</body>
</html>

templates/movie/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAIN</title>
    <script src="https://kit.fontawesome.com/b57dd44d80.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../static/css/search.css"/>
    <script src="../../static/js/play.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>     

<div class="overlay" >
    <div class="header">
        <a class="logo" href="/" style="text-decoration-line: none;">NETFLIX</a>
        <div class="nav">
            <a class="nav-item" href="/">홈</a>
            <a class="nav-item" href="#rate-ranking">상위 평점 영화</a>
            <a class="nav-item" href="#now_hottest">New! 요즘 대세영화</a>
            <a class="nav-item" href="#like-contents">내가 찜한 콘텐츠</a>
        </div>
        <div class="menu">
            <div id="search">
            <form method="get" action="{% url 'movie:search' %}" >
                <input type="search" name="kw" placeholder="검색">
            </form>
            </div>
            <div class="menu-item"> {{user.username}} </div>
            <a class="menu-item" href={% url 'logout' %} style="color:white; text-decoration-line: none;">
                Logout
            </a>
        </div>
    </div>
</div>


<div class="category-list" style="position:top">
    <div clas="wrapper">
        <div class="list-title" id="search-result"><h3> 검색결과 : <b>{{ query }}</b></h3></div>
        <div class="carousel">s
            <div class="carouselbox first">
                {% comment %}  {% endcomment %}
                {% for movie in movies %}
                    <div class="content">
                        {% comment %} <a href= "/movie/{{movie.url}}"> {% endcomment %}
                        <a href="{% url 'movie:recommend_movies' movie.pk %}">
                            <img class="img-0 slider-img" src="{{ movie.imgurl }}">
                            <!--Hover Content-->
                            <div class="video_content">
                                <div class="play_btn">
                                    <div class="vid_name">{{movie.title}}</div>
                                    <div class="vid_detail">
                                        <ul class="vid_list">
                                            <li class="c_green">{{movie.rate}}</li>
                                            <li class="br_round">{{movie.age}}</li>
                                            <li>{{movie.runningtime}}</li>
                                        </ul>
                                    </div>
                                    <div class="vid_category">
                                        <ul class="vid_list">
                                            {% for genre in genres%}
                                            <li>{{genre.genre_name}}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>                    
                {% endfor %}
            </div>
            <button class="switchLeft sliderButton" onclick="recommend.sliderScrollLeft()"></a>
            <button class="switchRight sliderButton" onclick="recommend.sliderScrollRight()">></button>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.0.0-alpha.1/axios.js"></script>
    <script src="../../static/js/index.js"></script>
</div>
</body>
</html>